---
abstract: 'Functions for accessing a hashes internal iterator.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  ExtUtils::CBuilder: '0'
  ExtUtils::ParseXS: '3.15'
  Test2::Bundle::Extended: '0'
  Test2::Tools::Spec: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hash-StoredIterator
provides:
  Hash::StoredIterator:
    file: lib/Hash/StoredIterator.pm
    version: 0.008_01
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/exodist/Hash-StoredIterator
version: 0.008_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
